[tableau]
token_name = "pseudo-netflix-app"
token_secret = "oh9AySmwS7uLm8XpVdaKAQ==:rwFg6O2JosQmtvRpsKex4lzVCVcYKqjA"
server_url = "https://abc01.online.tableau.com/"
site_id = "streamlit_write_page?:iid=1"

