[tableau]
token_name = "streamlit_netflix_pseudo_database"
token_secret = "skl4n2YUQqu/jBV0Qvoo2g==:G2CVLdSwdApVZQgXM1IheI8DeT6A2t51"
server_url = "https://abc01.online.tableau.com/"
site_id = "streamlit_write_page"
