import streamlit as st

st.title("Netflix User Pseudo-Database App")
st.write("The dataset gives a peek into a sample of Netflix users, showing their subscriptions, payments, join dates, and more, with additional insights into behavior and preferences, all for analysis within a hypothetical Netflix userbase.")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.write("")
st.image('netflix_logo_graphic.png',width=680)